<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Book;

class BooksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $books = [
            [
                'title_id'=>'1',
                'pub_id'=>'NXBT',
                'year'=>'2019',
                'price'=>'110000',
                'amount'=>'50',
                'image'=>'images/books/1.jpg',
                'describe'=>null,
                'promotion_id'=>null
            ],
            [
                'title_id'=>'2',
                'pub_id'=>'NXBT',
                'year'=>'2018',
                'price'=>'125000',
                'amount'=>'50',
                'image'=>'images/books/2.jpg',
                'describe'=>null,
                'promotion_id'=>null
            ],
            [
                'title_id'=>'3',
                'pub_id'=>'NXBT',
                'year'=>'2018',
                'price'=>'80000',
                'amount'=>'50',
                'image'=>'images/books/3.jpg',
                'describe'=>null,
                'promotion_id'=>null
            ],
            [
                'title_id'=>'4',
                'pub_id'=>'NXBT',
                'year'=>'2017',
                'price'=>'76000',
                'amount'=>'50',
                'image'=>'images/books/4.jpg',
                'describe'=>null,
                'promotion_id'=>'1'
            ],
            [
                'title_id'=>'5',
                'pub_id'=>'NXBT',
                'year'=>'2019',
                'price'=>'110000',
                'amount'=>'50',
                'image'=>'images/books/5.jpg',
                'describe'=>null,
                'promotion_id'=>1
            ],
            [
                'title_id'=>'6',
                'pub_id'=>'NXBT',
                'year'=>'2020',
                'price'=>'125000',
                'amount'=>'50',
                'image'=>'images/books/6.jpg',
                'describe'=>null,
                'promotion_id'=>'1'
            ],
            [
                'title_id'=>'7',
                'pub_id'=>'NXBPN',
                'year'=>'2016',
                'price'=>'54000',
                'amount'=>'50',
                'image'=>'images/books/7.jpg',
                'describe'=>null,
                'promotion_id'=>'1'
            ],
            [
                'title_id'=>'8',
                'pub_id'=>'NXBPN',
                'year'=>'2015',
                'price'=>'79000',
                'amount'=>'50',
                'image'=>'images/books/8.jpg',
                'describe'=>null,
                'promotion_id'=>null
            ],
            [
                'title_id'=>'9',
                'pub_id'=>'NXBPN',
                'year'=>'2014',
                'price'=>'46000',
                'amount'=>'50',
                'image'=>'images/books/9.jpg',
                'describe'=>null,
                'promotion_id'=>null
            ],
            [
                'title_id'=>'10',
                'pub_id'=>'NXBVH',
                'year'=>'2015',
                'price'=>'50000',
                'amount'=>'50',
                'image'=>'images/books/10.jpg',
                'describe'=>null,
                'promotion_id'=>null
            ],
            [
                'title_id'=>'11',
                'pub_id'=>'NXBTD',
                'year'=>'2014',
                'price'=>'59000',
                'amount'=>'50',
                'image'=>'images/books/11.jpg',
                'describe'=>null,
                'promotion_id'=>null
            ],
            [
                'title_id'=>'12',
                'pub_id'=>'NXBHNV',
                'year'=>'2016',
                'price'=>'120000',
                'amount'=>'50',
                'image'=>'images/books/12.jpg',
                'describe'=>null,
                'promotion_id'=>'1'
            ],
            [
                'title_id'=>'13',
                'pub_id'=>'NXBVH',
                'year'=>'2013',
                'price'=>'65000',
                'amount'=>'50',
                'image'=>'images/books/13.jpg',
                'describe'=>null,
                'promotion_id'=>null
            ],
            [
                'title_id'=>'14',
                'pub_id'=>'NXBVH',
                'year'=>'2015',
                'price'=>'85000',
                'amount'=>'50',
                'image'=>'images/books/14.jpg',
                'describe'=>null,
                'promotion_id'=>null
            ],
            [
                'title_id'=>'15',
                'pub_id'=>'NXBVHVN',
                'year'=>'2018',
                'price'=>'89000',
                'amount'=>'50',
                'image'=>'images/books/15.jpg',
                'describe'=>null,
                'promotion_id'=>'1'
            ],
            [
                'title_id'=>'16',
                'pub_id'=>'NXBVHVN',
                'year'=>'2016',
                'price'=>'89000',
                'amount'=>'50',
                'image'=>'images/books/16.jpg',
                'describe'=>null,
                'promotion_id'=>null
            ],
            [
                'title_id'=>'17',
                'pub_id'=>'NXBHNV',
                'year'=>'2013',
                'price'=>'36000',
                'amount'=>'50',
                'image'=>'images/books/17.jpg',
                'describe'=>null,
                'promotion_id'=>'1'
            ],
            [
                'title_id'=>'18',
                'pub_id'=>'NXBVH',
                'year'=>'2017',
                'price'=>'89000',
                'amount'=>'50',
                'image'=>'images/books/18.jpg',
                'describe'=>null,
                'promotion_id'=>null
            ],
            [
                'title_id'=>'19',
                'pub_id'=>'NXBHNV',
                'year'=>'2014',
                'price'=>'50000',
                'amount'=>'50',
                'image'=>'images/books/19.jpg',
                'describe'=>null,
                'promotion_id'=>null
            ],
            [
                'title_id'=>'20',
                'pub_id'=>'NXBVHVN',
                'year'=>'2014',
                'price'=>'78000',
                'amount'=>'50',
                'image'=>'images/books/20.jpg',
                'describe'=>null,
                'promotion_id'=>null
            ],
            [
                'title_id'=>'21',
                'pub_id'=>'NXBVHVN',
                'year'=>'2015',
                'price'=>'78000',
                'amount'=>'50',
                'image'=>'images/books/21.jpg',
                'describe'=>null,
                'promotion_id'=>'1'
            ],
            [
                'title_id'=>'22',
                'pub_id'=>'NXBVH',
                'year'=>'2014',
                'price'=>'87000',
                'amount'=>'50',
                'image'=>'images/books/22.jpg',
                'describe'=>null,
                'promotion_id'=>null
            ],
            [
                'title_id'=>'23',
                'pub_id'=>'NXBHN',
                'year'=>'2019',
                'price'=>'89000',
                'amount'=>'50',
                'image'=>'images/books/23.jpg',
                'describe'=>null,
                'promotion_id'=>null
            ],
            [
                'title_id'=>'24',
                'pub_id'=>'NXBVH',
                'year'=>'2013',
                'price'=>'60000',
                'amount'=>'50',
                'image'=>'images/books/24.jpg',
                'describe'=>null,
                'promotion_id'=>null
            ],
            [
                'title_id'=>'25',
                'pub_id'=>'NXBPN',
                'year'=>'2015',
                'price'=>'89000',
                'amount'=>'50',
                'image'=>'images/books/25.jpg',
                'describe'=>null,
                'promotion_id'=>'1'
            ],
            [
                'title_id'=>'26',
                'pub_id'=>'NXBPN',
                'year'=>'2018',
                'price'=>'86000',
                'amount'=>'50',
                'image'=>'images/books/26.jpg',
                'describe'=>null,
                'promotion_id'=>'1'
            ],
            [
                'title_id'=>'27',
                'pub_id'=>'NXBVH',
                'year'=>'2019',
                'price'=>'95000',
                'amount'=>'50',
                'image'=>'images/books/27.jpg',
                'describe'=>null,
                'promotion_id'=>'1'
            ],
        ];
  
        foreach ($books as $key => $value) {
            Book::create($value);
        }
    }
}