<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\CategoryBook;

class CategoryBooksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cate_book = [
            [
                'book_id'=>'1',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'2',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'3',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'4',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'5',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'6',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'7',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'8',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'9',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'10',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'11',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'12',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'13',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'14',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'15',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'16',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'17',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'18',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'19',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'20',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'21',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'22',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'23',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'24',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'25',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'26',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'27',
                'cate_id'=>'3',
            ],
            [
                'book_id'=>'1',
                'cate_id'=>'6',
            ],
            [
                'book_id'=>'2',
                'cate_id'=>'6',
            ],
            [
                'book_id'=>'3',
                'cate_id'=>'6',
            ],
            [
                'book_id'=>'4',
                'cate_id'=>'6',
            ],
            [
                'book_id'=>'5',
                'cate_id'=>'6',
            ],
            [
                'book_id'=>'6',
                'cate_id'=>'6',
            ],
            [
                'book_id'=>'7',
                'cate_id'=>'6',
            ],
        ];
  
        foreach ($cate_book as $key => $value) {
            CategoryBook::create($value);
        }
    }
}