<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\ImportDetail;

class ImportDetailsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $import_details = [
            [
                'import_id'=>'1',
                'book_id'=>'1',
                'amount'=>'50',
                'price'=>'90000',
            ],
            [
                'import_id'=>'1',
                'book_id'=>'2',
                'amount'=>'50',
                'price'=>'100000',
            ],
            [
                'import_id'=>'1',
                'book_id'=>'3',
                'amount'=>'50',
                'price'=>'70000',
            ],
            [
                'import_id'=>'1',
                'book_id'=>'4',
                'amount'=>'50',
                'price'=>'60000',
            ],
            [
                'import_id'=>'1',
                'book_id'=>'5',
                'amount'=>'50',
                'price'=>'100000',
            ],
            [
                'import_id'=>'1',
                'book_id'=>'6',
                'amount'=>'50',
                'price'=>'110000',
            ],
            [
                'import_id'=>'1',
                'book_id'=>'7',
                'amount'=>'50',
                'price'=>'40000',
            ],
            [
                'import_id'=>'1',
                'book_id'=>'8',
                'amount'=>'50',
                'price'=>'60000',
            ],
            [
                'import_id'=>'1',
                'book_id'=>'9',
                'amount'=>'50',
                'price'=>'30000',
            ],
            [
                'import_id'=>'1',
                'book_id'=>'10',
                'amount'=>'50',
                'price'=>'40000',
            ],
            [
                'import_id'=>'1',
                'book_id'=>'11',
                'amount'=>'50',
                'price'=>'40000',
            ],
            [
                'import_id'=>'1',
                'book_id'=>'12',
                'amount'=>'50',
                'price'=>'110000',
            ],
            [
                'import_id'=>'1',
                'book_id'=>'13',
                'amount'=>'50',
                'price'=>'50000',
            ],
            [
                'import_id'=>'1',
                'book_id'=>'14',
                'amount'=>'50',
                'price'=>'70000',
            ],
            [
                'import_id'=>'1',
                'book_id'=>'15',
                'amount'=>'50',
                'price'=>'70000',
            ],
            [
                'import_id'=>'1',
                'book_id'=>'16',
                'amount'=>'50',
                'price'=>'70000',
            ],
            [
                'import_id'=>'1',
                'book_id'=>'17',
                'amount'=>'50',
                'price'=>'20000',
            ],
            [
                'import_id'=>'1',
                'book_id'=>'18',
                'amount'=>'50',
                'price'=>'70000',
            ],
            [
                'import_id'=>'1',
                'book_id'=>'19',
                'amount'=>'50',
                'price'=>'40000',
            ],
            [
                'import_id'=>'1',
                'book_id'=>'20',
                'amount'=>'50',
                'price'=>'60000',
            ],
            [
                'import_id'=>'1',
                'book_id'=>'21',
                'amount'=>'50',
                'price'=>'60000',
            ],
            [
                'import_id'=>'1',
                'book_id'=>'22',
                'amount'=>'50',
                'price'=>'70000',
            ],
            [
                'import_id'=>'1',
                'book_id'=>'23',
                'amount'=>'50',
                'price'=>'70000',
            ],
            [
                'import_id'=>'1',
                'book_id'=>'24',
                'amount'=>'50',
                'price'=>'50000',
            ],
            [
                'import_id'=>'1',
                'book_id'=>'25',
                'amount'=>'50',
                'price'=>'70000',
            ],
            [
                'import_id'=>'1',
                'book_id'=>'26',
                'amount'=>'50',
                'price'=>'70000',
            ],
            [
                'import_id'=>'1',
                'book_id'=>'27',
                'amount'=>'50',
                'price'=>'80000',
            ],
        ];
  
        foreach ($import_details as $key => $value) {
            ImportDetail::create($value);
        }
    }
}